# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\DEV\elFrosh_repo\elFrosher\UI\main_layout_v2a.ui',
# licensing of 'C:\DEV\elFrosh_repo\elFrosher\UI\main_layout_v2a.ui' applies.
#
# Created: Mon Feb  4 18:21:17 2019
#      by: pyside2-uic  running on PySide2 5.11.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setContentsMargins(5, 10, 5, 7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.get_version = QtWidgets.QPushButton(self.centralwidget)
        self.get_version.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.get_version.setObjectName("get_version")
        self.buttons_layout.addWidget(self.get_version)
        self.chek_out = QtWidgets.QPushButton(self.centralwidget)
        self.chek_out.setObjectName("chek_out")
        self.buttons_layout.addWidget(self.chek_out)
        self.incement = QtWidgets.QPushButton(self.centralwidget)
        self.incement.setObjectName("incement")
        self.buttons_layout.addWidget(self.incement)
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setObjectName("submit")
        self.buttons_layout.addWidget(self.submit)
        spacerItem = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem)
        self.create_asset = QtWidgets.QPushButton(self.centralwidget)
        self.create_asset.setObjectName("create_asset")
        self.buttons_layout.addWidget(self.create_asset)
        spacerItem1 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem1)
        self.user_name = QtWidgets.QLabel(self.centralwidget)
        self.user_name.setObjectName("user_name")
        self.buttons_layout.addWidget(self.user_name)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem2)
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setEnabled(False)
        self.search.setObjectName("search")
        self.buttons_layout.addWidget(self.search)
        self.buttons_layout.setStretch(0, 1)
        self.buttons_layout.setStretch(2, 1)
        self.buttons_layout.setStretch(3, 1)
        self.buttons_layout.setStretch(8, 3)
        self.buttons_layout.setStretch(9, 5)
        self.verticalLayout_5.addLayout(self.buttons_layout)
        self.vertical_splitter = QtWidgets.QSplitter(self.centralwidget)
        self.vertical_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.vertical_splitter.setObjectName("vertical_splitter")
        self.horizontal_left_splitter = QtWidgets.QSplitter(self.vertical_splitter)
        self.horizontal_left_splitter.setOrientation(QtCore.Qt.Vertical)
        self.horizontal_left_splitter.setObjectName("horizontal_left_splitter")
        self.bookmarks = QtWidgets.QListView(self.horizontal_left_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bookmarks.sizePolicy().hasHeightForWidth())
        self.bookmarks.setSizePolicy(sizePolicy)
        self.bookmarks.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.bookmarks.setObjectName("bookmarks")
        self.trees_views = QtWidgets.QTabWidget(self.horizontal_left_splitter)
        self.trees_views.setObjectName("trees_views")
        self.workspace = QtWidgets.QWidget()
        self.workspace.setObjectName("workspace")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.workspace)
        self.verticalLayout_3.setContentsMargins(0, 2, 0, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.project_tree = QtWidgets.QTreeView(self.workspace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.project_tree.sizePolicy().hasHeightForWidth())
        self.project_tree.setSizePolicy(sizePolicy)
        self.project_tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.project_tree.setAlternatingRowColors(True)
        self.project_tree.setObjectName("project_tree")
        self.verticalLayout_3.addWidget(self.project_tree)
        self.trees_views.addTab(self.workspace, "")
        self.server = QtWidgets.QWidget()
        self.server.setObjectName("server")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.server)
        self.verticalLayout_4.setContentsMargins(0, 2, 0, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.server_tree = QtWidgets.QTreeView(self.server)
        self.server_tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.server_tree.setAlternatingRowColors(True)
        self.server_tree.setObjectName("server_tree")
        self.verticalLayout_4.addWidget(self.server_tree)
        self.trees_views.addTab(self.server, "")
        self.tabWidget = QtWidgets.QTabWidget(self.vertical_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_details = QtWidgets.QWidget()
        self.tab_details.setObjectName("tab_details")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_details)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pending_table = QtWidgets.QTableView(self.tab_details)
        self.pending_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pending_table.setAlternatingRowColors(True)
        self.pending_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.pending_table.setIconSize(QtCore.QSize(18, 18))
        self.pending_table.setShowGrid(False)
        self.pending_table.setGridStyle(QtCore.Qt.CustomDashLine)
        self.pending_table.setSortingEnabled(True)
        self.pending_table.setCornerButtonEnabled(False)
        self.pending_table.setObjectName("pending_table")
        self.pending_table.verticalHeader().setVisible(False)
        self.pending_table.verticalHeader().setDefaultSectionSize(22)
        self.verticalLayout.addWidget(self.pending_table)
        self.details_table = QtWidgets.QTableView(self.tab_details)
        self.details_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.details_table.setAlternatingRowColors(True)
        self.details_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.details_table.setIconSize(QtCore.QSize(18, 18))
        self.details_table.setShowGrid(False)
        self.details_table.setGridStyle(QtCore.Qt.CustomDashLine)
        self.details_table.setSortingEnabled(True)
        self.details_table.setCornerButtonEnabled(False)
        self.details_table.setObjectName("details_table")
        self.details_table.verticalHeader().setVisible(False)
        self.details_table.verticalHeader().setDefaultSectionSize(22)
        self.verticalLayout.addWidget(self.details_table)
        self.tabWidget.addTab(self.tab_details, "")
        self.tab_preview = QtWidgets.QWidget()
        self.tab_preview.setObjectName("tab_preview")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_preview)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.preview_pic = QtWidgets.QLabel(self.tab_preview)
        self.preview_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.preview_pic.setObjectName("preview_pic")
        self.verticalLayout_2.addWidget(self.preview_pic)
        self.comments_layout = QtWidgets.QHBoxLayout()
        self.comments_layout.setObjectName("comments_layout")
        self.label_comment = QtWidgets.QLabel(self.tab_preview)
        self.label_comment.setEnabled(False)
        self.label_comment.setObjectName("label_comment")
        self.comments_layout.addWidget(self.label_comment)
        self.comment_out = QtWidgets.QTextBrowser(self.tab_preview)
        self.comment_out.setEnabled(False)
        self.comment_out.setObjectName("comment_out")
        self.comments_layout.addWidget(self.comment_out)
        self.verticalLayout_2.addLayout(self.comments_layout)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_preview, "")
        self.verticalLayout_5.addWidget(self.vertical_splitter)
        self.verticalLayout_5.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.trees_views.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.get_version.setText(QtWidgets.QApplication.translate("MainWindow", "get", None, -1))
        self.chek_out.setText(QtWidgets.QApplication.translate("MainWindow", "chek out", None, -1))
        self.incement.setText(QtWidgets.QApplication.translate("MainWindow", "increment", None, -1))
        self.submit.setText(QtWidgets.QApplication.translate("MainWindow", "submit", None, -1))
        self.create_asset.setText(QtWidgets.QApplication.translate("MainWindow", "Folders", None, -1))
        self.user_name.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.search.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "search", None, -1))
        self.trees_views.setTabText(self.trees_views.indexOf(self.workspace), QtWidgets.QApplication.translate("MainWindow", "workspace", None, -1))
        self.trees_views.setTabText(self.trees_views.indexOf(self.server), QtWidgets.QApplication.translate("MainWindow", "server", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_details), QtWidgets.QApplication.translate("MainWindow", "Details", None, -1))
        self.preview_pic.setText(QtWidgets.QApplication.translate("MainWindow", "No Preview", None, -1))
        self.label_comment.setText(QtWidgets.QApplication.translate("MainWindow", "comment", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_preview), QtWidgets.QApplication.translate("MainWindow", "Preview", None, -1))

